# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_items(apps, schema_editor):
        I = apps.get_model("reciept", "Item")
        data = {"name": "Coffee",
                "company_came_from": "Java City",
                "price": 1.75}
        item = I(**data)
        item.save()

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('company_came_from', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.Item')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.RunPython(create_items),
    ]
