# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def create_items(apps, schema_editor):
        """ Used to create some common items/catagories on init """
        Catagory = apps.get_model("receipt", "Catagory")
        data = {"name": "Food"}
        food_catagory = Catagory(**data)
        food_catagory.save()
        data = {"name": "Computer/Technology"}
        tech_catagory = Catagory(**data)
        tech_catagory.save()
        data = {"name": "School Supplies"}
        school_supplies = Catagory(**data)
        school_supplies.save()

        I = apps.get_model("receipt", "Item")
        data = {"name": "Coffee",
                "company_came_from": "Java City",
                "price": 1.75,
                "catagory": food_catagory}
        item = I(**data)
        print item.price
        item.save()
        data = {"name": "Tofu",
                "company_came_from": "Hunan House",
                "price": 10.00,
                "catagory": food_catagory}
        item = I(**data)
        item.save()
        data = {"name": "Book",
                "company_came_from": "",
                "price": 8.00,
                "catagory": school_supplies}
        item = I(**data)
        item.save()
        data = {"name": "Veggie Sub",
                "company_came_from": "Subway",
                "price": 5.00,
                "catagory": food_catagory}
        item = I(**data)
        item.save()
        data = {"name": "Keyboard",
                "company_came_from": "Amazon",
                "price": 20.00,
                "catagory": tech_catagory}
        item = I(**data)
        item.save()

        Purchase = apps.get_model("receipt", "Purchase")
        coffee = I.objects.get(name="Coffee")
        coffee_purchase = Purchase(
            item_purchased=coffee, amount_payed=coffee.price)
        coffee_purchase.save()
        coffee = I.objects.get(name="Coffee")
        coffee.price = 2.00
        coffee.save()
        another_coffee_purchase = Purchase(
            item_purchased=coffee, amount_payed=coffee.price)
        another_coffee_purchase.save()

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('object_name', models.CharField(max_length=25, null=True)),
                ('undo_handler', models.CharField(choices=[('undo add item', 'Undo Add Item'), ('undo purchase', 'Undo Purchase')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('monthly_paycheck', models.DecimalField(decimal_places=2, max_digits=19)),
                ('monthly_saving_desired', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('company_came_from', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('number_of_times_purchased', models.IntegerField(blank=True, default=0)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.Catagory')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount_payed', models.DecimalField(decimal_places=2, max_digits=19)),
                ('item_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.Item')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('name', 'company_came_from', 'catagory')]),
        ),
        migrations.RunPython(create_items),
    ]
